development:
  adapter: postgresql
  database: bgstudio_development
  username: bgstudio
  password: bgstudio
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: bgstudio_test
  username: bgstudio
  password: bgstudio
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: bgstudio_production
  username: bgstudio
  password: bgstudio
  host: localhost
  encoding: UTF8

